version: '3.6'

services:

  calcard-server: 
    image: 'calcard-server'
    container_name: 'calcard-server'
    build: '../calcard-backend'
    ports:
      - '8080:8080'
      
  calcard-client:
    hostname: localhost
    image: 'calcard-client'
    container_name: 'calcard-client'
    build: '../calcard-frontend'
    ports:
      - '4200:80'